package com.whyse.lib.md;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \ufffd\ufffd\u05a4\ufffd\ufffd\ufffd\ufffd\u03f5\u0373\ufffd\ufffd\ufffd\u0379\ufffd\u02fe\ufffd\ufffd\u053f<br>
 * <i>native declaration : src\main\resources\lib\headfile\ThostFtdcUserApiStruct.h:2743</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Md") 
public class CThostFtdcCFMMCBrokerKeyField extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : TThostFtdcBrokerIDType */
	@Array({11}) 
	@Field(0) 
	public Pointer<Byte > BrokerID() {
		return this.io.getPointerField(this, 0);
	}
	/** C type : TThostFtdcParticipantIDType */
	@Array({11}) 
	@Field(1) 
	public Pointer<Byte > ParticipantID() {
		return this.io.getPointerField(this, 1);
	}
	/** C type : TThostFtdcDateType */
	@Array({9}) 
	@Field(2) 
	public Pointer<Byte > CreateDate() {
		return this.io.getPointerField(this, 2);
	}
	/** C type : TThostFtdcTimeType */
	@Array({9}) 
	@Field(3) 
	public Pointer<Byte > CreateTime() {
		return this.io.getPointerField(this, 3);
	}
	/** C type : TThostFtdcSequenceNoType */
	@Field(4) 
	public int KeyID() {
		return this.io.getIntField(this, 4);
	}
	/** C type : TThostFtdcSequenceNoType */
	@Field(4) 
	public CThostFtdcCFMMCBrokerKeyField KeyID(int KeyID) {
		this.io.setIntField(this, 4, KeyID);
		return this;
	}
	/** C type : TThostFtdcCFMMCKeyType */
	@Array({21}) 
	@Field(5) 
	public Pointer<Byte > CurrentKey() {
		return this.io.getPointerField(this, 5);
	}
	/** C type : TThostFtdcCFMMCKeyKindType */
	@Field(6) 
	public byte KeyKind() {
		return this.io.getByteField(this, 6);
	}
	/** C type : TThostFtdcCFMMCKeyKindType */
	@Field(6) 
	public CThostFtdcCFMMCBrokerKeyField KeyKind(byte KeyKind) {
		this.io.setByteField(this, 6, KeyKind);
		return this;
	}
	public CThostFtdcCFMMCBrokerKeyField() {
		super();
	}
	public CThostFtdcCFMMCBrokerKeyField(Pointer pointer) {
		super(pointer);
	}
}
