package com.whyse.lib.md;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0121\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
 * <i>native declaration : src\main\resources\lib\headfile\ThostFtdcUserApiStruct.h:2101</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Md") 
public class CThostFtdcMarketDataAsk45Field extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : TThostFtdcPriceType */
	@Field(0) 
	public double AskPrice4() {
		return this.io.getDoubleField(this, 0);
	}
	/** C type : TThostFtdcPriceType */
	@Field(0) 
	public CThostFtdcMarketDataAsk45Field AskPrice4(double AskPrice4) {
		this.io.setDoubleField(this, 0, AskPrice4);
		return this;
	}
	/** C type : TThostFtdcVolumeType */
	@Field(1) 
	public int AskVolume4() {
		return this.io.getIntField(this, 1);
	}
	/** C type : TThostFtdcVolumeType */
	@Field(1) 
	public CThostFtdcMarketDataAsk45Field AskVolume4(int AskVolume4) {
		this.io.setIntField(this, 1, AskVolume4);
		return this;
	}
	/** C type : TThostFtdcPriceType */
	@Field(2) 
	public double AskPrice5() {
		return this.io.getDoubleField(this, 2);
	}
	/** C type : TThostFtdcPriceType */
	@Field(2) 
	public CThostFtdcMarketDataAsk45Field AskPrice5(double AskPrice5) {
		this.io.setDoubleField(this, 2, AskPrice5);
		return this;
	}
	/** C type : TThostFtdcVolumeType */
	@Field(3) 
	public int AskVolume5() {
		return this.io.getIntField(this, 3);
	}
	/** C type : TThostFtdcVolumeType */
	@Field(3) 
	public CThostFtdcMarketDataAsk45Field AskVolume5(int AskVolume5) {
		this.io.setIntField(this, 3, AskVolume5);
		return this;
	}
	public CThostFtdcMarketDataAsk45Field() {
		super();
	}
	public CThostFtdcMarketDataAsk45Field(Pointer pointer) {
		super(pointer);
	}
}
