package com.whyse.lib.md;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \ufffd\ufffd\ufffd\ufffd<br>
 * <i>native declaration : src\main\resources\lib\headfile\ThostFtdcUserApiStruct.h:1774</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Md") 
public class CThostFtdcQuoteField extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : TThostFtdcBrokerIDType */
	@Array({11}) 
	@Field(0) 
	public Pointer<Byte > BrokerID() {
		return this.io.getPointerField(this, 0);
	}
	/** C type : TThostFtdcInvestorIDType */
	@Array({13}) 
	@Field(1) 
	public Pointer<Byte > InvestorID() {
		return this.io.getPointerField(this, 1);
	}
	/** C type : TThostFtdcInstrumentIDType */
	@Array({31}) 
	@Field(2) 
	public Pointer<Byte > InstrumentID() {
		return this.io.getPointerField(this, 2);
	}
	/** C type : TThostFtdcOrderRefType */
	@Array({13}) 
	@Field(3) 
	public Pointer<Byte > QuoteRef() {
		return this.io.getPointerField(this, 3);
	}
	/** C type : TThostFtdcUserIDType */
	@Array({16}) 
	@Field(4) 
	public Pointer<Byte > UserID() {
		return this.io.getPointerField(this, 4);
	}
	/** C type : TThostFtdcPriceType */
	@Field(5) 
	public double AskPrice() {
		return this.io.getDoubleField(this, 5);
	}
	/** C type : TThostFtdcPriceType */
	@Field(5) 
	public CThostFtdcQuoteField AskPrice(double AskPrice) {
		this.io.setDoubleField(this, 5, AskPrice);
		return this;
	}
	/** C type : TThostFtdcPriceType */
	@Field(6) 
	public double BidPrice() {
		return this.io.getDoubleField(this, 6);
	}
	/** C type : TThostFtdcPriceType */
	@Field(6) 
	public CThostFtdcQuoteField BidPrice(double BidPrice) {
		this.io.setDoubleField(this, 6, BidPrice);
		return this;
	}
	/** C type : TThostFtdcVolumeType */
	@Field(7) 
	public int AskVolume() {
		return this.io.getIntField(this, 7);
	}
	/** C type : TThostFtdcVolumeType */
	@Field(7) 
	public CThostFtdcQuoteField AskVolume(int AskVolume) {
		this.io.setIntField(this, 7, AskVolume);
		return this;
	}
	/** C type : TThostFtdcVolumeType */
	@Field(8) 
	public int BidVolume() {
		return this.io.getIntField(this, 8);
	}
	/** C type : TThostFtdcVolumeType */
	@Field(8) 
	public CThostFtdcQuoteField BidVolume(int BidVolume) {
		this.io.setIntField(this, 8, BidVolume);
		return this;
	}
	/** C type : TThostFtdcRequestIDType */
	@Field(9) 
	public int RequestID() {
		return this.io.getIntField(this, 9);
	}
	/** C type : TThostFtdcRequestIDType */
	@Field(9) 
	public CThostFtdcQuoteField RequestID(int RequestID) {
		this.io.setIntField(this, 9, RequestID);
		return this;
	}
	/** C type : TThostFtdcBusinessUnitType */
	@Array({21}) 
	@Field(10) 
	public Pointer<Byte > BusinessUnit() {
		return this.io.getPointerField(this, 10);
	}
	/** C type : TThostFtdcOffsetFlagType */
	@Field(11) 
	public byte AskOffsetFlag() {
		return this.io.getByteField(this, 11);
	}
	/** C type : TThostFtdcOffsetFlagType */
	@Field(11) 
	public CThostFtdcQuoteField AskOffsetFlag(byte AskOffsetFlag) {
		this.io.setByteField(this, 11, AskOffsetFlag);
		return this;
	}
	/** C type : TThostFtdcOffsetFlagType */
	@Field(12) 
	public byte BidOffsetFlag() {
		return this.io.getByteField(this, 12);
	}
	/** C type : TThostFtdcOffsetFlagType */
	@Field(12) 
	public CThostFtdcQuoteField BidOffsetFlag(byte BidOffsetFlag) {
		this.io.setByteField(this, 12, BidOffsetFlag);
		return this;
	}
	/** C type : TThostFtdcHedgeFlagType */
	@Field(13) 
	public byte AskHedgeFlag() {
		return this.io.getByteField(this, 13);
	}
	/** C type : TThostFtdcHedgeFlagType */
	@Field(13) 
	public CThostFtdcQuoteField AskHedgeFlag(byte AskHedgeFlag) {
		this.io.setByteField(this, 13, AskHedgeFlag);
		return this;
	}
	/** C type : TThostFtdcHedgeFlagType */
	@Field(14) 
	public byte BidHedgeFlag() {
		return this.io.getByteField(this, 14);
	}
	/** C type : TThostFtdcHedgeFlagType */
	@Field(14) 
	public CThostFtdcQuoteField BidHedgeFlag(byte BidHedgeFlag) {
		this.io.setByteField(this, 14, BidHedgeFlag);
		return this;
	}
	/** C type : TThostFtdcOrderLocalIDType */
	@Array({13}) 
	@Field(15) 
	public Pointer<Byte > QuoteLocalID() {
		return this.io.getPointerField(this, 15);
	}
	/** C type : TThostFtdcExchangeIDType */
	@Array({9}) 
	@Field(16) 
	public Pointer<Byte > ExchangeID() {
		return this.io.getPointerField(this, 16);
	}
	/** C type : TThostFtdcParticipantIDType */
	@Array({11}) 
	@Field(17) 
	public Pointer<Byte > ParticipantID() {
		return this.io.getPointerField(this, 17);
	}
	/** C type : TThostFtdcClientIDType */
	@Array({11}) 
	@Field(18) 
	public Pointer<Byte > ClientID() {
		return this.io.getPointerField(this, 18);
	}
	/** C type : TThostFtdcExchangeInstIDType */
	@Array({31}) 
	@Field(19) 
	public Pointer<Byte > ExchangeInstID() {
		return this.io.getPointerField(this, 19);
	}
	/** C type : TThostFtdcTraderIDType */
	@Array({21}) 
	@Field(20) 
	public Pointer<Byte > TraderID() {
		return this.io.getPointerField(this, 20);
	}
	/** C type : TThostFtdcInstallIDType */
	@Field(21) 
	public int InstallID() {
		return this.io.getIntField(this, 21);
	}
	/** C type : TThostFtdcInstallIDType */
	@Field(21) 
	public CThostFtdcQuoteField InstallID(int InstallID) {
		this.io.setIntField(this, 21, InstallID);
		return this;
	}
	/** C type : TThostFtdcSequenceNoType */
	@Field(22) 
	public int NotifySequence() {
		return this.io.getIntField(this, 22);
	}
	/** C type : TThostFtdcSequenceNoType */
	@Field(22) 
	public CThostFtdcQuoteField NotifySequence(int NotifySequence) {
		this.io.setIntField(this, 22, NotifySequence);
		return this;
	}
	/** C type : TThostFtdcOrderSubmitStatusType */
	@Field(23) 
	public byte OrderSubmitStatus() {
		return this.io.getByteField(this, 23);
	}
	/** C type : TThostFtdcOrderSubmitStatusType */
	@Field(23) 
	public CThostFtdcQuoteField OrderSubmitStatus(byte OrderSubmitStatus) {
		this.io.setByteField(this, 23, OrderSubmitStatus);
		return this;
	}
	/** C type : TThostFtdcDateType */
	@Array({9}) 
	@Field(24) 
	public Pointer<Byte > TradingDay() {
		return this.io.getPointerField(this, 24);
	}
	/** C type : TThostFtdcSettlementIDType */
	@Field(25) 
	public int SettlementID() {
		return this.io.getIntField(this, 25);
	}
	/** C type : TThostFtdcSettlementIDType */
	@Field(25) 
	public CThostFtdcQuoteField SettlementID(int SettlementID) {
		this.io.setIntField(this, 25, SettlementID);
		return this;
	}
	/** C type : TThostFtdcOrderSysIDType */
	@Array({21}) 
	@Field(26) 
	public Pointer<Byte > QuoteSysID() {
		return this.io.getPointerField(this, 26);
	}
	/** C type : TThostFtdcDateType */
	@Array({9}) 
	@Field(27) 
	public Pointer<Byte > InsertDate() {
		return this.io.getPointerField(this, 27);
	}
	/** C type : TThostFtdcTimeType */
	@Array({9}) 
	@Field(28) 
	public Pointer<Byte > InsertTime() {
		return this.io.getPointerField(this, 28);
	}
	/** C type : TThostFtdcTimeType */
	@Array({9}) 
	@Field(29) 
	public Pointer<Byte > CancelTime() {
		return this.io.getPointerField(this, 29);
	}
	/** C type : TThostFtdcOrderStatusType */
	@Field(30) 
	public byte QuoteStatus() {
		return this.io.getByteField(this, 30);
	}
	/** C type : TThostFtdcOrderStatusType */
	@Field(30) 
	public CThostFtdcQuoteField QuoteStatus(byte QuoteStatus) {
		this.io.setByteField(this, 30, QuoteStatus);
		return this;
	}
	/** C type : TThostFtdcParticipantIDType */
	@Array({11}) 
	@Field(31) 
	public Pointer<Byte > ClearingPartID() {
		return this.io.getPointerField(this, 31);
	}
	/** C type : TThostFtdcSequenceNoType */
	@Field(32) 
	public int SequenceNo() {
		return this.io.getIntField(this, 32);
	}
	/** C type : TThostFtdcSequenceNoType */
	@Field(32) 
	public CThostFtdcQuoteField SequenceNo(int SequenceNo) {
		this.io.setIntField(this, 32, SequenceNo);
		return this;
	}
	/** C type : TThostFtdcOrderSysIDType */
	@Array({21}) 
	@Field(33) 
	public Pointer<Byte > AskOrderSysID() {
		return this.io.getPointerField(this, 33);
	}
	/** C type : TThostFtdcOrderSysIDType */
	@Array({21}) 
	@Field(34) 
	public Pointer<Byte > BidOrderSysID() {
		return this.io.getPointerField(this, 34);
	}
	/** C type : TThostFtdcFrontIDType */
	@Field(35) 
	public int FrontID() {
		return this.io.getIntField(this, 35);
	}
	/** C type : TThostFtdcFrontIDType */
	@Field(35) 
	public CThostFtdcQuoteField FrontID(int FrontID) {
		this.io.setIntField(this, 35, FrontID);
		return this;
	}
	/** C type : TThostFtdcSessionIDType */
	@Field(36) 
	public int SessionID() {
		return this.io.getIntField(this, 36);
	}
	/** C type : TThostFtdcSessionIDType */
	@Field(36) 
	public CThostFtdcQuoteField SessionID(int SessionID) {
		this.io.setIntField(this, 36, SessionID);
		return this;
	}
	/** C type : TThostFtdcProductInfoType */
	@Array({11}) 
	@Field(37) 
	public Pointer<Byte > UserProductInfo() {
		return this.io.getPointerField(this, 37);
	}
	/** C type : TThostFtdcErrorMsgType */
	@Array({81}) 
	@Field(38) 
	public Pointer<Byte > StatusMsg() {
		return this.io.getPointerField(this, 38);
	}
	/** C type : TThostFtdcUserIDType */
	@Array({16}) 
	@Field(39) 
	public Pointer<Byte > ActiveUserID() {
		return this.io.getPointerField(this, 39);
	}
	/** C type : TThostFtdcSequenceNoType */
	@Field(40) 
	public int BrokerQuoteSeq() {
		return this.io.getIntField(this, 40);
	}
	/** C type : TThostFtdcSequenceNoType */
	@Field(40) 
	public CThostFtdcQuoteField BrokerQuoteSeq(int BrokerQuoteSeq) {
		this.io.setIntField(this, 40, BrokerQuoteSeq);
		return this;
	}
	/** C type : TThostFtdcOrderRefType */
	@Array({13}) 
	@Field(41) 
	public Pointer<Byte > AskOrderRef() {
		return this.io.getPointerField(this, 41);
	}
	/** C type : TThostFtdcOrderRefType */
	@Array({13}) 
	@Field(42) 
	public Pointer<Byte > BidOrderRef() {
		return this.io.getPointerField(this, 42);
	}
	/** C type : TThostFtdcOrderSysIDType */
	@Array({21}) 
	@Field(43) 
	public Pointer<Byte > ForQuoteSysID() {
		return this.io.getPointerField(this, 43);
	}
	public CThostFtdcQuoteField() {
		super();
	}
	public CThostFtdcQuoteField(Pointer pointer) {
		super(pointer);
	}
}
