package com.whyse.lib.md;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \ufffd\ufffd\u046f\ufffd\ufffd\ufffd\u0379\ufffd\u02fe\ufffd\u00fb\ufffd\ufffd\u00bc\ufffd<br>
 * <i>native declaration : src\main\resources\lib\headfile\ThostFtdcUserApiStruct.h:2352</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Md") 
public class CThostFtdcBrokerUserEventField extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : TThostFtdcBrokerIDType */
	@Array({11}) 
	@Field(0) 
	public Pointer<Byte > BrokerID() {
		return this.io.getPointerField(this, 0);
	}
	/** C type : TThostFtdcUserIDType */
	@Array({16}) 
	@Field(1) 
	public Pointer<Byte > UserID() {
		return this.io.getPointerField(this, 1);
	}
	/** C type : TThostFtdcUserEventTypeType */
	@Field(2) 
	public byte UserEventType() {
		return this.io.getByteField(this, 2);
	}
	/** C type : TThostFtdcUserEventTypeType */
	@Field(2) 
	public CThostFtdcBrokerUserEventField UserEventType(byte UserEventType) {
		this.io.setByteField(this, 2, UserEventType);
		return this;
	}
	/** C type : TThostFtdcSequenceNoType */
	@Field(3) 
	public int EventSequenceNo() {
		return this.io.getIntField(this, 3);
	}
	/** C type : TThostFtdcSequenceNoType */
	@Field(3) 
	public CThostFtdcBrokerUserEventField EventSequenceNo(int EventSequenceNo) {
		this.io.setIntField(this, 3, EventSequenceNo);
		return this;
	}
	/** C type : TThostFtdcDateType */
	@Array({9}) 
	@Field(4) 
	public Pointer<Byte > EventDate() {
		return this.io.getPointerField(this, 4);
	}
	/** C type : TThostFtdcTimeType */
	@Array({9}) 
	@Field(5) 
	public Pointer<Byte > EventTime() {
		return this.io.getPointerField(this, 5);
	}
	/** C type : TThostFtdcUserEventInfoType */
	@Array({1025}) 
	@Field(6) 
	public Pointer<Byte > UserEventInfo() {
		return this.io.getPointerField(this, 6);
	}
	/** C type : TThostFtdcInvestorIDType */
	@Array({13}) 
	@Field(7) 
	public Pointer<Byte > InvestorID() {
		return this.io.getPointerField(this, 7);
	}
	/** C type : TThostFtdcInstrumentIDType */
	@Array({31}) 
	@Field(8) 
	public Pointer<Byte > InstrumentID() {
		return this.io.getPointerField(this, 8);
	}
	public CThostFtdcBrokerUserEventField() {
		super();
	}
	public CThostFtdcBrokerUserEventField(Pointer pointer) {
		super(pointer);
	}
}
