package com.whyse.lib.trader;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0335\ufffd\u046f\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
 * <i>native declaration : src\main\resources\lib\headfile\ThostFtdcUserApiStruct.h:1899</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Trader") 
public class CThostFtdcForQuoteRspField extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : TThostFtdcDateType */
	@Array({9}) 
	@Field(0) 
	public Pointer<Byte > TradingDay() {
		return this.io.getPointerField(this, 0);
	}
	/** C type : TThostFtdcInstrumentIDType */
	@Array({31}) 
	@Field(1) 
	public Pointer<Byte > InstrumentID() {
		return this.io.getPointerField(this, 1);
	}
	/** C type : TThostFtdcOrderSysIDType */
	@Array({21}) 
	@Field(2) 
	public Pointer<Byte > ForQuoteSysID() {
		return this.io.getPointerField(this, 2);
	}
	/** C type : TThostFtdcTimeType */
	@Array({9}) 
	@Field(3) 
	public Pointer<Byte > ForQuoteTime() {
		return this.io.getPointerField(this, 3);
	}
	/** C type : TThostFtdcDateType */
	@Array({9}) 
	@Field(4) 
	public Pointer<Byte > ActionDay() {
		return this.io.getPointerField(this, 4);
	}
	/** C type : TThostFtdcExchangeIDType */
	@Array({9}) 
	@Field(5) 
	public Pointer<Byte > ExchangeID() {
		return this.io.getPointerField(this, 5);
	}
	public CThostFtdcForQuoteRspField() {
		super();
	}
	public CThostFtdcForQuoteRspField(Pointer pointer) {
		super(pointer);
	}
}
