package com.whyse.lib.trader;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \u0368\u0476\ufffd\u05f6\ufffd<br>
 * <i>native declaration : src\main\resources\lib\headfile\ThostFtdcUserApiStruct.h:580</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Trader") 
public class CThostFtdcCommPhaseField extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : TThostFtdcDateType */
	@Array({9}) 
	@Field(0) 
	public Pointer<Byte > TradingDay() {
		return this.io.getPointerField(this, 0);
	}
	/** C type : TThostFtdcCommPhaseNoType */
	@Field(1) 
	public short CommPhaseNo() {
		return this.io.getShortField(this, 1);
	}
	/** C type : TThostFtdcCommPhaseNoType */
	@Field(1) 
	public CThostFtdcCommPhaseField CommPhaseNo(short CommPhaseNo) {
		this.io.setShortField(this, 1, CommPhaseNo);
		return this;
	}
	/** C type : TThostFtdcSystemIDType */
	@Array({21}) 
	@Field(2) 
	public Pointer<Byte > SystemID() {
		return this.io.getPointerField(this, 2);
	}
	public CThostFtdcCommPhaseField() {
		super();
	}
	public CThostFtdcCommPhaseField(Pointer pointer) {
		super(pointer);
	}
}
