package com.whyse.lib.trader;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \ufffd\ufffd\ufffd\ufffd\u04ef\ufffd\ufffd\ufffd\u3de8<br>
 * <i>native declaration : src\main\resources\lib\headfile\ThostFtdcUserApiStruct.h:2147</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Trader") 
public class CThostFtdcPositionProfitAlgorithmField extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : TThostFtdcBrokerIDType */
	@Array({11}) 
	@Field(0) 
	public Pointer<Byte > BrokerID() {
		return this.io.getPointerField(this, 0);
	}
	/** C type : TThostFtdcAccountIDType */
	@Array({13}) 
	@Field(1) 
	public Pointer<Byte > AccountID() {
		return this.io.getPointerField(this, 1);
	}
	/** C type : TThostFtdcAlgorithmType */
	@Field(2) 
	public byte Algorithm() {
		return this.io.getByteField(this, 2);
	}
	/** C type : TThostFtdcAlgorithmType */
	@Field(2) 
	public CThostFtdcPositionProfitAlgorithmField Algorithm(byte Algorithm) {
		this.io.setByteField(this, 2, Algorithm);
		return this;
	}
	/** C type : TThostFtdcMemoType */
	@Array({161}) 
	@Field(3) 
	public Pointer<Byte > Memo() {
		return this.io.getPointerField(this, 3);
	}
	/** C type : TThostFtdcCurrencyIDType */
	@Array({4}) 
	@Field(4) 
	public Pointer<Byte > CurrencyID() {
		return this.io.getPointerField(this, 4);
	}
	public CThostFtdcPositionProfitAlgorithmField() {
		super();
	}
	public CThostFtdcPositionProfitAlgorithmField(Pointer pointer) {
		super(pointer);
	}
}
