package com.whyse.lib.trader;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u05a4\ufffd\ufffd\ufffd\ufffd<br>
 * <i>native declaration : src\main\resources\lib\headfile\ThostFtdcUserApiStruct.h:536</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Trader") 
public class CThostFtdcExchangeMarginRateField extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : TThostFtdcBrokerIDType */
	@Array({11}) 
	@Field(0) 
	public Pointer<Byte > BrokerID() {
		return this.io.getPointerField(this, 0);
	}
	/** C type : TThostFtdcInstrumentIDType */
	@Array({31}) 
	@Field(1) 
	public Pointer<Byte > InstrumentID() {
		return this.io.getPointerField(this, 1);
	}
	/** C type : TThostFtdcHedgeFlagType */
	@Field(2) 
	public byte HedgeFlag() {
		return this.io.getByteField(this, 2);
	}
	/** C type : TThostFtdcHedgeFlagType */
	@Field(2) 
	public CThostFtdcExchangeMarginRateField HedgeFlag(byte HedgeFlag) {
		this.io.setByteField(this, 2, HedgeFlag);
		return this;
	}
	/** C type : TThostFtdcRatioType */
	@Field(3) 
	public double LongMarginRatioByMoney() {
		return this.io.getDoubleField(this, 3);
	}
	/** C type : TThostFtdcRatioType */
	@Field(3) 
	public CThostFtdcExchangeMarginRateField LongMarginRatioByMoney(double LongMarginRatioByMoney) {
		this.io.setDoubleField(this, 3, LongMarginRatioByMoney);
		return this;
	}
	/** C type : TThostFtdcMoneyType */
	@Field(4) 
	public double LongMarginRatioByVolume() {
		return this.io.getDoubleField(this, 4);
	}
	/** C type : TThostFtdcMoneyType */
	@Field(4) 
	public CThostFtdcExchangeMarginRateField LongMarginRatioByVolume(double LongMarginRatioByVolume) {
		this.io.setDoubleField(this, 4, LongMarginRatioByVolume);
		return this;
	}
	/** C type : TThostFtdcRatioType */
	@Field(5) 
	public double ShortMarginRatioByMoney() {
		return this.io.getDoubleField(this, 5);
	}
	/** C type : TThostFtdcRatioType */
	@Field(5) 
	public CThostFtdcExchangeMarginRateField ShortMarginRatioByMoney(double ShortMarginRatioByMoney) {
		this.io.setDoubleField(this, 5, ShortMarginRatioByMoney);
		return this;
	}
	/** C type : TThostFtdcMoneyType */
	@Field(6) 
	public double ShortMarginRatioByVolume() {
		return this.io.getDoubleField(this, 6);
	}
	/** C type : TThostFtdcMoneyType */
	@Field(6) 
	public CThostFtdcExchangeMarginRateField ShortMarginRatioByVolume(double ShortMarginRatioByVolume) {
		this.io.setDoubleField(this, 6, ShortMarginRatioByVolume);
		return this;
	}
	public CThostFtdcExchangeMarginRateField() {
		super();
	}
	public CThostFtdcExchangeMarginRateField(Pointer pointer) {
		super(pointer);
	}
}
