package com.whyse.lib.trader;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \ufffd\ufffd\u00bc\ufffd\ufffd\u03e2<br>
 * <i>native declaration : src\main\resources\lib\headfile\ThostFtdcUserApiStruct.h:604</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Trader") 
public class CThostFtdcLoginInfoField extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : TThostFtdcFrontIDType */
	@Field(0) 
	public int FrontID() {
		return this.io.getIntField(this, 0);
	}
	/** C type : TThostFtdcFrontIDType */
	@Field(0) 
	public CThostFtdcLoginInfoField FrontID(int FrontID) {
		this.io.setIntField(this, 0, FrontID);
		return this;
	}
	/** C type : TThostFtdcSessionIDType */
	@Field(1) 
	public int SessionID() {
		return this.io.getIntField(this, 1);
	}
	/** C type : TThostFtdcSessionIDType */
	@Field(1) 
	public CThostFtdcLoginInfoField SessionID(int SessionID) {
		this.io.setIntField(this, 1, SessionID);
		return this;
	}
	/** C type : TThostFtdcBrokerIDType */
	@Array({11}) 
	@Field(2) 
	public Pointer<Byte > BrokerID() {
		return this.io.getPointerField(this, 2);
	}
	/** C type : TThostFtdcUserIDType */
	@Array({16}) 
	@Field(3) 
	public Pointer<Byte > UserID() {
		return this.io.getPointerField(this, 3);
	}
	/** C type : TThostFtdcDateType */
	@Array({9}) 
	@Field(4) 
	public Pointer<Byte > LoginDate() {
		return this.io.getPointerField(this, 4);
	}
	/** C type : TThostFtdcTimeType */
	@Array({9}) 
	@Field(5) 
	public Pointer<Byte > LoginTime() {
		return this.io.getPointerField(this, 5);
	}
	/** C type : TThostFtdcIPAddressType */
	@Array({16}) 
	@Field(6) 
	public Pointer<Byte > IPAddress() {
		return this.io.getPointerField(this, 6);
	}
	/** C type : TThostFtdcProductInfoType */
	@Array({11}) 
	@Field(7) 
	public Pointer<Byte > UserProductInfo() {
		return this.io.getPointerField(this, 7);
	}
	/** C type : TThostFtdcProductInfoType */
	@Array({11}) 
	@Field(8) 
	public Pointer<Byte > InterfaceProductInfo() {
		return this.io.getPointerField(this, 8);
	}
	/** C type : TThostFtdcProtocolInfoType */
	@Array({11}) 
	@Field(9) 
	public Pointer<Byte > ProtocolInfo() {
		return this.io.getPointerField(this, 9);
	}
	/** C type : TThostFtdcSystemNameType */
	@Array({41}) 
	@Field(10) 
	public Pointer<Byte > SystemName() {
		return this.io.getPointerField(this, 10);
	}
	/** C type : TThostFtdcPasswordType */
	@Array({41}) 
	@Field(11) 
	public Pointer<Byte > Password() {
		return this.io.getPointerField(this, 11);
	}
	/** C type : TThostFtdcOrderRefType */
	@Array({13}) 
	@Field(12) 
	public Pointer<Byte > MaxOrderRef() {
		return this.io.getPointerField(this, 12);
	}
	/** C type : TThostFtdcTimeType */
	@Array({9}) 
	@Field(13) 
	public Pointer<Byte > SHFETime() {
		return this.io.getPointerField(this, 13);
	}
	/** C type : TThostFtdcTimeType */
	@Array({9}) 
	@Field(14) 
	public Pointer<Byte > DCETime() {
		return this.io.getPointerField(this, 14);
	}
	/** C type : TThostFtdcTimeType */
	@Array({9}) 
	@Field(15) 
	public Pointer<Byte > CZCETime() {
		return this.io.getPointerField(this, 15);
	}
	/** C type : TThostFtdcTimeType */
	@Array({9}) 
	@Field(16) 
	public Pointer<Byte > FFEXTime() {
		return this.io.getPointerField(this, 16);
	}
	/** C type : TThostFtdcMacAddressType */
	@Array({21}) 
	@Field(17) 
	public Pointer<Byte > MacAddress() {
		return this.io.getPointerField(this, 17);
	}
	/** C type : TThostFtdcPasswordType */
	@Array({41}) 
	@Field(18) 
	public Pointer<Byte > OneTimePassword() {
		return this.io.getPointerField(this, 18);
	}
	/** C type : TThostFtdcTimeType */
	@Array({9}) 
	@Field(19) 
	public Pointer<Byte > INETime() {
		return this.io.getPointerField(this, 19);
	}
	/** C type : TThostFtdcBoolType */
	@Field(20) 
	public int IsQryControl() {
		return this.io.getIntField(this, 20);
	}
	/** C type : TThostFtdcBoolType */
	@Field(20) 
	public CThostFtdcLoginInfoField IsQryControl(int IsQryControl) {
		this.io.setIntField(this, 20, IsQryControl);
		return this;
	}
	public CThostFtdcLoginInfoField() {
		super();
	}
	public CThostFtdcLoginInfoField(Pointer pointer) {
		super(pointer);
	}
}
