package com.whyse.lib.trader;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \ufffd\ufffd\ufffd\u0379\ufffd\u02fe\ufffd\ufffd\ufffd\u05f2\ufffd\ufffd\ufffd<br>
 * <i>native declaration : src\main\resources\lib\headfile\ThostFtdcUserApiStruct.h:2693</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Trader") 
public class CThostFtdcBrokerTradingParamsField extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : TThostFtdcBrokerIDType */
	@Array({11}) 
	@Field(0) 
	public Pointer<Byte > BrokerID() {
		return this.io.getPointerField(this, 0);
	}
	/** C type : TThostFtdcInvestorIDType */
	@Array({13}) 
	@Field(1) 
	public Pointer<Byte > InvestorID() {
		return this.io.getPointerField(this, 1);
	}
	/** C type : TThostFtdcMarginPriceTypeType */
	@Field(2) 
	public byte MarginPriceType() {
		return this.io.getByteField(this, 2);
	}
	/** C type : TThostFtdcMarginPriceTypeType */
	@Field(2) 
	public CThostFtdcBrokerTradingParamsField MarginPriceType(byte MarginPriceType) {
		this.io.setByteField(this, 2, MarginPriceType);
		return this;
	}
	/** C type : TThostFtdcAlgorithmType */
	@Field(3) 
	public byte Algorithm() {
		return this.io.getByteField(this, 3);
	}
	/** C type : TThostFtdcAlgorithmType */
	@Field(3) 
	public CThostFtdcBrokerTradingParamsField Algorithm(byte Algorithm) {
		this.io.setByteField(this, 3, Algorithm);
		return this;
	}
	/** C type : TThostFtdcIncludeCloseProfitType */
	@Field(4) 
	public byte AvailIncludeCloseProfit() {
		return this.io.getByteField(this, 4);
	}
	/** C type : TThostFtdcIncludeCloseProfitType */
	@Field(4) 
	public CThostFtdcBrokerTradingParamsField AvailIncludeCloseProfit(byte AvailIncludeCloseProfit) {
		this.io.setByteField(this, 4, AvailIncludeCloseProfit);
		return this;
	}
	/** C type : TThostFtdcCurrencyIDType */
	@Array({4}) 
	@Field(5) 
	public Pointer<Byte > CurrencyID() {
		return this.io.getPointerField(this, 5);
	}
	/** C type : TThostFtdcOptionRoyaltyPriceTypeType */
	@Field(6) 
	public byte OptionRoyaltyPriceType() {
		return this.io.getByteField(this, 6);
	}
	/** C type : TThostFtdcOptionRoyaltyPriceTypeType */
	@Field(6) 
	public CThostFtdcBrokerTradingParamsField OptionRoyaltyPriceType(byte OptionRoyaltyPriceType) {
		this.io.setByteField(this, 6, OptionRoyaltyPriceType);
		return this;
	}
	public CThostFtdcBrokerTradingParamsField() {
		super();
	}
	public CThostFtdcBrokerTradingParamsField(Pointer pointer) {
		super(pointer);
	}
}
