package com.whyse.lib.trader;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \ufffd\ufffd\ufffd\u0379\ufffd\u02fe\ufffd\u02bd\ufffd<br>
 * <i>native declaration : src\main\resources\lib\headfile\ThostFtdcUserApiStruct.h:2729</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Trader") 
public class CThostFtdcBrokerDepositField extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : TThostFtdcTradeDateType */
	@Array({9}) 
	@Field(0) 
	public Pointer<Byte > TradingDay() {
		return this.io.getPointerField(this, 0);
	}
	/** C type : TThostFtdcBrokerIDType */
	@Array({11}) 
	@Field(1) 
	public Pointer<Byte > BrokerID() {
		return this.io.getPointerField(this, 1);
	}
	/** C type : TThostFtdcParticipantIDType */
	@Array({11}) 
	@Field(2) 
	public Pointer<Byte > ParticipantID() {
		return this.io.getPointerField(this, 2);
	}
	/** C type : TThostFtdcExchangeIDType */
	@Array({9}) 
	@Field(3) 
	public Pointer<Byte > ExchangeID() {
		return this.io.getPointerField(this, 3);
	}
	/** C type : TThostFtdcMoneyType */
	@Field(4) 
	public double PreBalance() {
		return this.io.getDoubleField(this, 4);
	}
	/** C type : TThostFtdcMoneyType */
	@Field(4) 
	public CThostFtdcBrokerDepositField PreBalance(double PreBalance) {
		this.io.setDoubleField(this, 4, PreBalance);
		return this;
	}
	/** C type : TThostFtdcMoneyType */
	@Field(5) 
	public double CurrMargin() {
		return this.io.getDoubleField(this, 5);
	}
	/** C type : TThostFtdcMoneyType */
	@Field(5) 
	public CThostFtdcBrokerDepositField CurrMargin(double CurrMargin) {
		this.io.setDoubleField(this, 5, CurrMargin);
		return this;
	}
	/** C type : TThostFtdcMoneyType */
	@Field(6) 
	public double CloseProfit() {
		return this.io.getDoubleField(this, 6);
	}
	/** C type : TThostFtdcMoneyType */
	@Field(6) 
	public CThostFtdcBrokerDepositField CloseProfit(double CloseProfit) {
		this.io.setDoubleField(this, 6, CloseProfit);
		return this;
	}
	/** C type : TThostFtdcMoneyType */
	@Field(7) 
	public double Balance() {
		return this.io.getDoubleField(this, 7);
	}
	/** C type : TThostFtdcMoneyType */
	@Field(7) 
	public CThostFtdcBrokerDepositField Balance(double Balance) {
		this.io.setDoubleField(this, 7, Balance);
		return this;
	}
	/** C type : TThostFtdcMoneyType */
	@Field(8) 
	public double Deposit() {
		return this.io.getDoubleField(this, 8);
	}
	/** C type : TThostFtdcMoneyType */
	@Field(8) 
	public CThostFtdcBrokerDepositField Deposit(double Deposit) {
		this.io.setDoubleField(this, 8, Deposit);
		return this;
	}
	/** C type : TThostFtdcMoneyType */
	@Field(9) 
	public double Withdraw() {
		return this.io.getDoubleField(this, 9);
	}
	/** C type : TThostFtdcMoneyType */
	@Field(9) 
	public CThostFtdcBrokerDepositField Withdraw(double Withdraw) {
		this.io.setDoubleField(this, 9, Withdraw);
		return this;
	}
	/** C type : TThostFtdcMoneyType */
	@Field(10) 
	public double Available() {
		return this.io.getDoubleField(this, 10);
	}
	/** C type : TThostFtdcMoneyType */
	@Field(10) 
	public CThostFtdcBrokerDepositField Available(double Available) {
		this.io.setDoubleField(this, 10, Available);
		return this;
	}
	/** C type : TThostFtdcMoneyType */
	@Field(11) 
	public double Reserve() {
		return this.io.getDoubleField(this, 11);
	}
	/** C type : TThostFtdcMoneyType */
	@Field(11) 
	public CThostFtdcBrokerDepositField Reserve(double Reserve) {
		this.io.setDoubleField(this, 11, Reserve);
		return this;
	}
	/** C type : TThostFtdcMoneyType */
	@Field(12) 
	public double FrozenMargin() {
		return this.io.getDoubleField(this, 12);
	}
	/** C type : TThostFtdcMoneyType */
	@Field(12) 
	public CThostFtdcBrokerDepositField FrozenMargin(double FrozenMargin) {
		this.io.setDoubleField(this, 12, FrozenMargin);
		return this;
	}
	public CThostFtdcBrokerDepositField() {
		super();
	}
	public CThostFtdcBrokerDepositField(Pointer pointer) {
		super(pointer);
	}
}
