package com.whyse.lib.trader;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u027d\ufffd<br>
 * <i>native declaration : src\main\resources\lib\headfile\ThostFtdcUserApiStruct.h:865</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Trader") 
public class CThostFtdcExchangeTradeField extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : TThostFtdcExchangeIDType */
	@Array({9}) 
	@Field(0) 
	public Pointer<Byte > ExchangeID() {
		return this.io.getPointerField(this, 0);
	}
	/** C type : TThostFtdcTradeIDType */
	@Array({21}) 
	@Field(1) 
	public Pointer<Byte > TradeID() {
		return this.io.getPointerField(this, 1);
	}
	/** C type : TThostFtdcDirectionType */
	@Field(2) 
	public byte Direction() {
		return this.io.getByteField(this, 2);
	}
	/** C type : TThostFtdcDirectionType */
	@Field(2) 
	public CThostFtdcExchangeTradeField Direction(byte Direction) {
		this.io.setByteField(this, 2, Direction);
		return this;
	}
	/** C type : TThostFtdcOrderSysIDType */
	@Array({21}) 
	@Field(3) 
	public Pointer<Byte > OrderSysID() {
		return this.io.getPointerField(this, 3);
	}
	/** C type : TThostFtdcParticipantIDType */
	@Array({11}) 
	@Field(4) 
	public Pointer<Byte > ParticipantID() {
		return this.io.getPointerField(this, 4);
	}
	/** C type : TThostFtdcClientIDType */
	@Array({11}) 
	@Field(5) 
	public Pointer<Byte > ClientID() {
		return this.io.getPointerField(this, 5);
	}
	/** C type : TThostFtdcTradingRoleType */
	@Field(6) 
	public byte TradingRole() {
		return this.io.getByteField(this, 6);
	}
	/** C type : TThostFtdcTradingRoleType */
	@Field(6) 
	public CThostFtdcExchangeTradeField TradingRole(byte TradingRole) {
		this.io.setByteField(this, 6, TradingRole);
		return this;
	}
	/** C type : TThostFtdcExchangeInstIDType */
	@Array({31}) 
	@Field(7) 
	public Pointer<Byte > ExchangeInstID() {
		return this.io.getPointerField(this, 7);
	}
	/** C type : TThostFtdcOffsetFlagType */
	@Field(8) 
	public byte OffsetFlag() {
		return this.io.getByteField(this, 8);
	}
	/** C type : TThostFtdcOffsetFlagType */
	@Field(8) 
	public CThostFtdcExchangeTradeField OffsetFlag(byte OffsetFlag) {
		this.io.setByteField(this, 8, OffsetFlag);
		return this;
	}
	/** C type : TThostFtdcHedgeFlagType */
	@Field(9) 
	public byte HedgeFlag() {
		return this.io.getByteField(this, 9);
	}
	/** C type : TThostFtdcHedgeFlagType */
	@Field(9) 
	public CThostFtdcExchangeTradeField HedgeFlag(byte HedgeFlag) {
		this.io.setByteField(this, 9, HedgeFlag);
		return this;
	}
	/** C type : TThostFtdcPriceType */
	@Field(10) 
	public double Price() {
		return this.io.getDoubleField(this, 10);
	}
	/** C type : TThostFtdcPriceType */
	@Field(10) 
	public CThostFtdcExchangeTradeField Price(double Price) {
		this.io.setDoubleField(this, 10, Price);
		return this;
	}
	/** C type : TThostFtdcVolumeType */
	@Field(11) 
	public int Volume() {
		return this.io.getIntField(this, 11);
	}
	/** C type : TThostFtdcVolumeType */
	@Field(11) 
	public CThostFtdcExchangeTradeField Volume(int Volume) {
		this.io.setIntField(this, 11, Volume);
		return this;
	}
	/** C type : TThostFtdcDateType */
	@Array({9}) 
	@Field(12) 
	public Pointer<Byte > TradeDate() {
		return this.io.getPointerField(this, 12);
	}
	/** C type : TThostFtdcTimeType */
	@Array({9}) 
	@Field(13) 
	public Pointer<Byte > TradeTime() {
		return this.io.getPointerField(this, 13);
	}
	/** C type : TThostFtdcTradeTypeType */
	@Field(14) 
	public byte TradeType() {
		return this.io.getByteField(this, 14);
	}
	/** C type : TThostFtdcTradeTypeType */
	@Field(14) 
	public CThostFtdcExchangeTradeField TradeType(byte TradeType) {
		this.io.setByteField(this, 14, TradeType);
		return this;
	}
	/** C type : TThostFtdcPriceSourceType */
	@Field(15) 
	public byte PriceSource() {
		return this.io.getByteField(this, 15);
	}
	/** C type : TThostFtdcPriceSourceType */
	@Field(15) 
	public CThostFtdcExchangeTradeField PriceSource(byte PriceSource) {
		this.io.setByteField(this, 15, PriceSource);
		return this;
	}
	/** C type : TThostFtdcTraderIDType */
	@Array({21}) 
	@Field(16) 
	public Pointer<Byte > TraderID() {
		return this.io.getPointerField(this, 16);
	}
	/** C type : TThostFtdcOrderLocalIDType */
	@Array({13}) 
	@Field(17) 
	public Pointer<Byte > OrderLocalID() {
		return this.io.getPointerField(this, 17);
	}
	/** C type : TThostFtdcParticipantIDType */
	@Array({11}) 
	@Field(18) 
	public Pointer<Byte > ClearingPartID() {
		return this.io.getPointerField(this, 18);
	}
	/** C type : TThostFtdcBusinessUnitType */
	@Array({21}) 
	@Field(19) 
	public Pointer<Byte > BusinessUnit() {
		return this.io.getPointerField(this, 19);
	}
	/** C type : TThostFtdcSequenceNoType */
	@Field(20) 
	public int SequenceNo() {
		return this.io.getIntField(this, 20);
	}
	/** C type : TThostFtdcSequenceNoType */
	@Field(20) 
	public CThostFtdcExchangeTradeField SequenceNo(int SequenceNo) {
		this.io.setIntField(this, 20, SequenceNo);
		return this;
	}
	/** C type : TThostFtdcTradeSourceType */
	@Field(21) 
	public byte TradeSource() {
		return this.io.getByteField(this, 21);
	}
	/** C type : TThostFtdcTradeSourceType */
	@Field(21) 
	public CThostFtdcExchangeTradeField TradeSource(byte TradeSource) {
		this.io.setByteField(this, 21, TradeSource);
		return this;
	}
	public CThostFtdcExchangeTradeField() {
		super();
	}
	public CThostFtdcExchangeTradeField(Pointer pointer) {
		super(pointer);
	}
}
