package com.whyse.lib.trader;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \ufffd\ufffd\u01f0\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
 * <i>native declaration : src\main\resources\lib\headfile\ThostFtdcUserApiStruct.h:3949</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Trader") 
public class CThostFtdcCurrTransferIdentityField extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : TThostFtdcDRIdentityIDType */
	@Field(0) 
	public int IdentityID() {
		return this.io.getIntField(this, 0);
	}
	/** C type : TThostFtdcDRIdentityIDType */
	@Field(0) 
	public CThostFtdcCurrTransferIdentityField IdentityID(int IdentityID) {
		this.io.setIntField(this, 0, IdentityID);
		return this;
	}
	public CThostFtdcCurrTransferIdentityField() {
		super();
	}
	public CThostFtdcCurrTransferIdentityField(Pointer pointer) {
		super(pointer);
	}
}
