package com.whyse.lib.trader;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \ufffd\u00fb\ufffd\ufffd\ufffd\u00bc\ufffd\ufffd\ufffd\ufffd<br>
 * <i>native declaration : src\main\resources\lib\headfile\ThostFtdcUserApiStruct.h:17</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Trader") 
public class CThostFtdcReqUserLoginField extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : TThostFtdcDateType */
	@Array({9}) 
	@Field(0) 
	public Pointer<Byte > TradingDay() {
		return this.io.getPointerField(this, 0);
	}
	/** C type : TThostFtdcBrokerIDType */
	@Array({11}) 
	@Field(1) 
	public Pointer<Byte > BrokerID() {
		return this.io.getPointerField(this, 1);
	}
	/** C type : TThostFtdcUserIDType */
	@Array({16}) 
	@Field(2) 
	public Pointer<Byte > UserID() {
		return this.io.getPointerField(this, 2);
	}
	/** C type : TThostFtdcPasswordType */
	@Array({41}) 
	@Field(3) 
	public Pointer<Byte > Password() {
		return this.io.getPointerField(this, 3);
	}
	/** C type : TThostFtdcProductInfoType */
	@Array({11}) 
	@Field(4) 
	public Pointer<Byte > UserProductInfo() {
		return this.io.getPointerField(this, 4);
	}
	/** C type : TThostFtdcProductInfoType */
	@Array({11}) 
	@Field(5) 
	public Pointer<Byte > InterfaceProductInfo() {
		return this.io.getPointerField(this, 5);
	}
	/** C type : TThostFtdcProtocolInfoType */
	@Array({11}) 
	@Field(6) 
	public Pointer<Byte > ProtocolInfo() {
		return this.io.getPointerField(this, 6);
	}
	/** C type : TThostFtdcMacAddressType */
	@Array({21}) 
	@Field(7) 
	public Pointer<Byte > MacAddress() {
		return this.io.getPointerField(this, 7);
	}
	/** C type : TThostFtdcPasswordType */
	@Array({41}) 
	@Field(8) 
	public Pointer<Byte > OneTimePassword() {
		return this.io.getPointerField(this, 8);
	}
	/** C type : TThostFtdcIPAddressType */
	@Array({16}) 
	@Field(9) 
	public Pointer<Byte > ClientIPAddress() {
		return this.io.getPointerField(this, 9);
	}
	public CThostFtdcReqUserLoginField() {
		super();
	}
	public CThostFtdcReqUserLoginField(Pointer pointer) {
		super(pointer);
	}
}
