package com.whyse.lib.trader;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \ufffd\ufffd\ufffd\u0379\ufffd\u02fe\ufffd\u00fb\ufffd<br>
 * <i>native declaration : src\main\resources\lib\headfile\ThostFtdcUserApiStruct.h:470</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("Trader") 
public class CThostFtdcBrokerUserField extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : TThostFtdcBrokerIDType */
	@Array({11}) 
	@Field(0) 
	public Pointer<Byte > BrokerID() {
		return this.io.getPointerField(this, 0);
	}
	/** C type : TThostFtdcUserIDType */
	@Array({16}) 
	@Field(1) 
	public Pointer<Byte > UserID() {
		return this.io.getPointerField(this, 1);
	}
	/** C type : TThostFtdcUserNameType */
	@Array({81}) 
	@Field(2) 
	public Pointer<Byte > UserName() {
		return this.io.getPointerField(this, 2);
	}
	/** C type : TThostFtdcUserTypeType */
	@Field(3) 
	public byte UserType() {
		return this.io.getByteField(this, 3);
	}
	/** C type : TThostFtdcUserTypeType */
	@Field(3) 
	public CThostFtdcBrokerUserField UserType(byte UserType) {
		this.io.setByteField(this, 3, UserType);
		return this;
	}
	/** C type : TThostFtdcBoolType */
	@Field(4) 
	public int IsActive() {
		return this.io.getIntField(this, 4);
	}
	/** C type : TThostFtdcBoolType */
	@Field(4) 
	public CThostFtdcBrokerUserField IsActive(int IsActive) {
		this.io.setIntField(this, 4, IsActive);
		return this;
	}
	/** C type : TThostFtdcBoolType */
	@Field(5) 
	public int IsUsingOTP() {
		return this.io.getIntField(this, 5);
	}
	/** C type : TThostFtdcBoolType */
	@Field(5) 
	public CThostFtdcBrokerUserField IsUsingOTP(int IsUsingOTP) {
		this.io.setIntField(this, 5, IsUsingOTP);
		return this;
	}
	public CThostFtdcBrokerUserField() {
		super();
	}
	public CThostFtdcBrokerUserField(Pointer pointer) {
		super(pointer);
	}
}
